#!/usr/bin/env sh

NAME=fastapi-app
DIR=/usr/local/www/regionalMap
USER=louis
GROUP=louis
WORKERS=5
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv-map/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=debug

cd $DIR
. $VENV 

exec /usr/local/bin/gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=$DIR/logs/gunicorn-fastapi.log

